url: "https://mich8060.github.io/projects"
baseurl: "/projects"

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

title: Pluralsight Prototype     
description: A virtual proof that name is awesome!  