url: "https://mich8060.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

title: Pluralsight Prototype     
description: A virtual proof that name is awesome!
email: mich8060@hotmail.com   

permalink: /notes/:year/:month/:day/:title
markdown: kramdown

date_format: 'ordinal'     # July 3rd, 2014
time_format: '%-I:%M %P'   # 2:08 pm